"""
Layer 1b — Market Regime: VIX-based risk filter.

Uses yfinance only. The result is intentionally small and cached because the
nightly scanner may run hundreds of ticker analyses in separate processes.
"""
import json
import os
from datetime import datetime, timedelta

import pandas as pd


def _load_cache(cache_path: str, max_age_hours: int) -> dict | None:
    if not cache_path or not os.path.exists(cache_path):
        return None
    try:
        with open(cache_path) as f:
            payload = json.load(f)
        fetched_at = datetime.fromisoformat(payload.get("fetched_at", ""))
        if datetime.now() - fetched_at <= timedelta(hours=max_age_hours):
            return payload.get("data")
    except Exception:
        return None
    return None


def _save_cache(cache_path: str, data: dict) -> None:
    if not cache_path:
        return
    try:
        os.makedirs(os.path.dirname(cache_path), exist_ok=True)
        with open(cache_path, "w") as f:
            json.dump({"fetched_at": datetime.now().isoformat(), "data": data}, f, indent=2)
    except Exception:
        pass


def _classify_vix(value: float, trend: str) -> tuple[str, str, float]:
    if value >= 30:
        return "extreme", "defensive", 0.45 if trend == "rising" else 0.55
    if value >= 22:
        return "high", "reduce_risk", 0.65 if trend == "rising" else 0.75
    if value <= 14:
        return "low", "risk_on", 1.10
    return "normal", "normal", 1.00


def fetch_exchange_rate(base: str = 'USD', quote: str = 'KRW') -> dict:
    """토스증권 API로 환율 조회.
    Returns:
        dict with 'rate', 'mid_rate', 'change_type', 'valid_from', 'valid_until', 'warnings'
    """
    result = {
        'rate': None,
        'mid_rate': None,
        'change_type': None,
        'valid_from': None,
        'valid_until': None,
        'warnings': [],
    }
    from toss_loader import get_toss_client
    client = get_toss_client()
    if client is None:
        result['warnings'].append('토스 클라이언트 미설정(MARGIN_TA_TOSS_IMPORT) — 환율 스킵')
        return result
    try:
        fx = client.get_exchange_rate(base, quote)
        result['rate'] = float(fx.get('rate', 0))
        result['mid_rate'] = float(fx.get('midRate', 0))
        result['change_type'] = fx.get('rateChangeType')
        result['valid_from'] = fx.get('validFrom')
        result['valid_until'] = fx.get('validUntil')
    except Exception as e:
        result['warnings'].append(f'토스 환율 조회 실패: {e}')
    return result


def fetch_vix_regime(cache_path: str | None = None, max_age_hours: int = 4) -> dict:
    """
    Fetch VIX daily data and return a compact market regime package.

    Returns:
        dict with value, regime, trend, risk_mode, size_multiplier, warnings.
    """
    cached = _load_cache(cache_path, max_age_hours) if cache_path else None
    if cached:
        return cached

    result = {
        "symbol": "^VIX",
        "value": None,
        "regime": "unavailable",
        "trend": "unknown",
        "risk_mode": "normal",
        "size_multiplier": 1.0,
        "warnings": [],
    }

    try:
        import yfinance as yf

        df = yf.Ticker("^VIX").history(period="1y", interval="1d")
        if df.empty or "Close" not in df:
            result["warnings"].append("VIX 데이터 없음")
            return result

        close = df["Close"].dropna()
        if len(close) < 20:
            result["warnings"].append("VIX 데이터 부족")
            return result

        value = float(close.iloc[-1])
        ema5 = close.ewm(span=5, adjust=False).mean()
        ema10 = close.ewm(span=10, adjust=False).mean()
        ema_gap = (float(ema5.iloc[-1]) / float(ema10.iloc[-1]) - 1) * 100

        if ema_gap > 2:
            trend = "rising"
        elif ema_gap < -2:
            trend = "falling"
        else:
            trend = "flat"

        regime, risk_mode, size_multiplier = _classify_vix(value, trend)
        percentile_1y = round((close <= value).mean() * 100, 1)

        result.update({
            "value": round(value, 2),
            "regime": regime,
            "trend": trend,
            "risk_mode": risk_mode,
            "size_multiplier": size_multiplier,
            "ema5": round(float(ema5.iloc[-1]), 2),
            "ema10": round(float(ema10.iloc[-1]), 2),
            "percentile_1y": percentile_1y,
            "as_of": close.index[-1].isoformat() if hasattr(close.index[-1], "isoformat") else str(close.index[-1]),
        })
        _save_cache(cache_path, result)
        return result
    except Exception as e:
        result["warnings"].append(f"VIX 조회 실패: {e}")
        return result


def load_market_breadth(cache_path: str, max_age_hours: int = 36) -> dict:
    """Load cached breadth regime generated by update_market_breadth.py."""
    cached = _load_cache(cache_path, max_age_hours)
    if cached:
        return cached
    return {
        "regime": "unavailable",
        "risk_mode": "normal",
        "size_multiplier": 1.0,
        "warnings": [f"Market breadth 캐시 없음 또는 만료: {cache_path}"],
    }


def compute_market_breadth(tickers: list[str], period: str = "1y") -> dict:
    """
    Compute cross-sectional breadth from a supplied ticker universe.

    This is intended for nightly/cache use, not per-ticker realtime execution.
    """
    result = {
        "universe_size": len(tickers),
        "valid_tickers": 0,
        "above_50ma_pct": None,
        "above_200ma_pct": None,
        "ad_line_slope_20d": None,
        "regime": "unavailable",
        "risk_mode": "normal",
        "size_multiplier": 1.0,
        "warnings": [],
    }

    if not tickers:
        result["warnings"].append("breadth ticker universe empty")
        return result

    try:
        import yfinance as yf

        data = yf.download(
            tickers,
            period=period,
            interval="1d",
            auto_adjust=True,
            progress=False,
            threads=True,
            group_by="column",
        )

        if data.empty:
            result["warnings"].append("breadth download empty")
            return result

        close = data["Close"] if isinstance(data.columns, pd.MultiIndex) else data[["Close"]]
        if isinstance(close, pd.Series):
            close = close.to_frame()
        close = close.dropna(axis=1, how="all")
        result["valid_tickers"] = int(close.shape[1])
        if close.shape[1] == 0 or len(close) < 50:
            result["warnings"].append("breadth close history insufficient")
            return result

        last = close.iloc[-1]
        ma50 = close.rolling(50).mean().iloc[-1]
        above_50 = (last > ma50).dropna()
        result["above_50ma_pct"] = round(float(above_50.mean() * 100), 1) if len(above_50) else None

        if len(close) >= 200:
            ma200 = close.rolling(200).mean().iloc[-1]
            above_200 = (last > ma200).dropna()
            result["above_200ma_pct"] = round(float(above_200.mean() * 100), 1) if len(above_200) else None

        advancers = (close.diff() > 0).sum(axis=1)
        decliners = (close.diff() < 0).sum(axis=1)
        ad_line = (advancers - decliners).cumsum()
        if len(ad_line) >= 21:
            slope_20d = float(ad_line.iloc[-1] - ad_line.iloc[-21])
            result["ad_line_slope_20d"] = round(slope_20d, 2)
            if slope_20d > result["valid_tickers"] * 0.5:
                ad_trend = "rising"
            elif slope_20d < -result["valid_tickers"] * 0.5:
                ad_trend = "falling"
            else:
                ad_trend = "flat"
        else:
            ad_trend = "unknown"
        result["ad_line_trend"] = ad_trend

        above_200 = result["above_200ma_pct"]
        above_50 = result["above_50ma_pct"]
        if above_200 is not None and above_200 >= 60 and ad_trend != "falling":
            regime, risk_mode, multiplier = "strong", "risk_on", 1.10
        elif above_200 is not None and above_200 < 35:
            regime, risk_mode, multiplier = "weak", "reduce_risk", 0.70
        elif above_50 is not None and above_50 < 35 and ad_trend == "falling":
            regime, risk_mode, multiplier = "deteriorating", "reduce_risk", 0.80
        else:
            regime, risk_mode, multiplier = "neutral", "normal", 1.00

        result.update({
            "regime": regime,
            "risk_mode": risk_mode,
            "size_multiplier": multiplier,
            "as_of": close.index[-1].isoformat() if hasattr(close.index[-1], "isoformat") else str(close.index[-1]),
        })
        return result
    except Exception as e:
        result["warnings"].append(f"Market breadth 계산 실패: {e}")
        return result


def combine_market_regimes(vix: dict | None, breadth: dict | None) -> dict:
    """Create one conservative sizing filter from VIX and breadth regimes."""
    vix = vix or {}
    breadth = breadth or {}
    vix_mult = float(vix.get("size_multiplier", 1.0) or 1.0)
    breadth_mult = float(breadth.get("size_multiplier", 1.0) or 1.0)
    multiplier = min(vix_mult, breadth_mult)

    if multiplier < 0.7:
        risk_mode = "defensive"
    elif multiplier < 1.0:
        risk_mode = "reduce_risk"
    elif multiplier > 1.0:
        risk_mode = "risk_on"
    else:
        risk_mode = "normal"

    return {
        "regime": f"vix:{vix.get('regime', 'n/a')} / breadth:{breadth.get('regime', 'n/a')}",
        "trend": f"vix:{vix.get('trend', 'n/a')} / ad:{breadth.get('ad_line_trend', 'n/a')}",
        "risk_mode": risk_mode,
        "size_multiplier": multiplier,
    }
